spring.application.name=Enotes-API-Service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/enotes_uat?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 


# File Configuration
file.upload.path=notes/
spring.servlet.multipart.max-file-size=10000MB
spring.servlet.multipart.max-request-size=10000MB

# Email send configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=businesswithchitti@gmail.com
spring.mail.password=wzuqeaegivjgwmdy
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true

#Server port 
server.address=0.0.0.0